name: Buscar ELB com Tag

on:
  workflow_dispatch:

jobs:
  buscar-elb:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION}}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    environment:
      name: ${{ github.ref_name }}

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Buscar ELB com tag e salvar DNS em env
        run: |
          for elb in $(aws elb describe-load-balancers --query 'LoadBalancerDescriptions[].LoadBalancerName' --output text); do
            tag_value=$(aws elb describe-tags --load-balancer-names "$elb" \
              --query "TagDescriptions[0].Tags[?Key=='service'].Value" --output text)

            if [ "$tag_value" == "snackbar-management-prod" ]; then
              dns_name=$(aws elb describe-load-balancers --load-balancer-names "$elb" \
                --query 'LoadBalancerDescriptions[0].DNSName' --output text)

              echo "Encontrado ELB: $elb"
              echo "DNS: $dns_name"
              echo "DNS_NAME=$dns_name" >> $GITHUB_ENV
              break
            fi
          done
