name: Initial Setup

on:
  workflow_dispatch:

jobs:
  setup-bucket:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Configure S3 Bucket
        continue-on-error: true
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
            BUCKET_S3: ${{ secrets.BUCKET_S3 }}
        run: |
          aws s3api create-bucket --bucket ${{ secrets.BUCKET_S3 }} --region us-east-1

  install-helm-chart:
    runs-on: ubuntu-latest
    needs: setup-bucket
    environment:
      name: ${{ github.ref_name }}
    if: always()

    steps:
      - name: Checkout Kubernetes Repo
        uses: actions/checkout@v3
        with:
          repository: 'fiap-9soat-snackbar/eks'
          token: ${{ secrets.GH_TOKEN}}          
          
      - name: Init Helm
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
            BUCKET_S3: ${{ secrets.BUCKET_S3 }}
        run: |
          helm plugin install https://github.com/hypnoglow/helm-s3.git
          helm s3 init s3://${{ secrets.BUCKET_S3 }} --ignore-if-exists
          helm repo add snackbar-charts s3://${{ secrets.BUCKET_S3 }}
          helm package helm-chart/snackbar-app/
          helm s3 push snackbar-app-1.0.0.tgz snackbar-charts --force
          
