name: MongoDB Restore and Test Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-mongo-restore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DB Repo
        uses: actions/checkout@v3
        with:
          repository: 'fiap-9soat-snackbar/snackbar-database'
          token: ${{ secrets.GH_TOKEN}}

      - name: Obter o IP do runner
        run: |
              IP=$(curl -s ifconfig.me)
              echo "O IP do runner é: $IP"
              sleep 30

      - name: Install MongoDB CLI
        run: |
              wget -qO- https://www.mongodb.org/static/pgp/server-8.0.asc | sudo tee /etc/apt/trusted.gpg.d/server-8.0.asc
              echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
              sudo apt-get update
              sudo apt-get install -y mongodb-mongosh



      - name: Run MongoDB Restore Script
        env:
          MONGODB_USER: ${{ secrets.MONGODB_USER }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        run: |
          mongosh "mongodb+srv://snackbar-tcfase03-dev.0acxv.mongodb.net" \
          --username $MONGODB_USER \
          --password $MONGODB_PASSWORD \
          --eval "load('02-products-restore.js')"
