name: MongoDB Restore and Test Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-mongo-restore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DB Repo
        uses: actions/checkout@v3
        with:
          repository: 'fiap-9soat-snackbar/snackbar-database'
          token: ${{ secrets.GH_TOKEN}}

      - name: Run MongoDB Restore Script
        env:
          MONGODB_USER: ${{ secrets.MONGODB_USER }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        run: |
          mongo "mongodb+srv://snackbar-tcfase03-dev.0acxv.mongodb.net" \
          --username $MONGODB_USER \
          --password $MONGODB_PASSWORD \
          --eval "load('02-products-restore.js')"
